[FEATURE] Allow widgets to be rearranged #9
yashchaudhari008/minime pull request #13
Opened 2024-01-31 10:51 UTC by HappyLife2

## Changes Made

### Feature: Allow Widgets to be Rearranged #9

- Implemented drag-and-drop functionality for rearranging widgets.
- Added vanilla JavaScript code in index.html for drag-and-drop functionality, similar to https://glitch.com/~simple-drag-drop.
- Introduced a new component, DraggableWidget, in WidgetHolder.tsx to wrap widgets with drag-and-drop capabilities.
- Utilized DndProvider from react-dnd for enabling drag-and-drop functionality.
- Resolved TypeScript errors in DraggableWidget.tsx by explicitly defining the type of the draggedItem parameter.
- Updated tsconfig.json to include the correct types for react-dnd-html5-backend.
- Installed @types/react-dnd-html5-backend to resolve TypeScript errors related to missing type definitions.
- Updated package.json to include @types/react-dnd-html5-backend in devDependencies.
- Ensured App.tsx and main.tsx remain unchanged as they were not directly related to the drag-and-drop feature.

### Overall Summary

- Implemented a user-requested feature for widget rearrangement.
- Resolved TypeScript errors and ensured the code adheres to best practices.
- Verified the smooth execution of the drag-and-drop feature.

2024-01-31 11:20 UTC, yashchaudhari008 commented
@HappyLife2  We do not use npm, we use yarn. Could you make the necessary changes before I review your work?

2024-01-31 12:48 UTC, HappyLife2 commented
@yashchaudhari008 I have made another commit with the changes requested, Kindly check them and let me know if any modification is needed, I honestly don't know how GitHub works as I'm still new to it pull and push requests, Kindly check and advise.

2024-01-31 13:19 UTC, yashchaudhari008 commented
Can we talk over discord/Gmail? rather than continuing the discussion here?

2024-01-31 13:21 UTC, HappyLife2 commented
Yes sure, you can find me on discord at "satan3581".

2024-01-31 15:50 UTC, yashchaudhari008 commented on src/components/WidgetHolder/WidgetHolder.tsx
> +};
Keep this inside WidgetHolder as it was before.

2024-01-31 15:53 UTC, yashchaudhari008 commented on src/components/WidgetHolder/WidgetHolder.tsx
> +	const [, ref] = useDrag({
this looks weird, can you add the proper variable rather than keeping it empty

2024-01-31 15:54 UTC, yashchaudhari008 commented on src/components/WidgetHolder/WidgetHolder.tsx
> +		type: "WIDGET",
Can you elaborate what does type do here?

2024-01-31 15:54 UTC, yashchaudhari008 commented on src/components/WidgetHolder/WidgetHolder.tsx
> +	const [, drop] = useDrop({
same here

2024-01-31 15:59 UTC, yashchaudhari008 commented on src/components/WidgetHolder/WidgetHolder.tsx
> +		<DndProvider backend={HTML5Backend}>
This DndProvider could be wrapped around widgetsData itself as we need drag and drop only in that region

2024-01-31 16:03 UTC, yashchaudhari008 requested changes
Here are few more issues:
- [ ] After page is refreshed , rearrangement is lost
- [ ] There is clipped border when bookmark is dragged.

2024-02-02 06:39 UTC, closed without merging

2024-02-02 06:41 UTC, yashchaudhari008 commented
Work will be continued in [9-allow-widget-rearrangement](https://github.com/yashchaudhari008/minime/tree/9-allow-widget-rearrangement) branch.

Thanks, @HappyLife2 for contributing