add(feature): Footer component
yashchaudhari008/minime pull request #8
Opened 2024-01-27 13:48 UTC by linyers

New feature for issue https://github.com/yashchaudhari008/minime/issues/7

Contain:

- Footer component
- Footer scss module designs
- Github icon component
- Github repository page link
- yashchaudhari008 github profile link
- Contributors page link

![2024-01-27-104804_649x62_scrot](https://github.com/yashchaudhari008/minime/assets/134330318/e74e3827-df31-4365-b67e-bded34dd2ea6)

2024-01-29 14:04 UTC, yashchaudhari008 commented on src/App.tsx
> +import Footer from "./components/Footer/Footer";
Move this import above styles

2024-01-29 14:04 UTC, yashchaudhari008 commented on src/components/Footer/Footer.tsx
> +				Made with ♥ by{" "}
```suggestion
				Made with ♥ by
```

2024-01-29 14:04 UTC, yashchaudhari008 commented on src/components/Footer/Footer.tsx
> +				&{" "}
```suggestion
				</a>
				&
```

2024-01-29 14:04 UTC, yashchaudhari008 commented on src/components/Footer/Footer.tsx
> +					<GithubIcon /> Github Page
Use `<FontAwesomeIcon icon={faGithub} className={styles.icon} />` . You might need to add `@fortawesome/free-brands-svg-icons` to add `faGithub` icon

References:
- https://fontawesome.com/docs/web/use-with/react/add-icons#add-individual-icons-explicitly
- You can also look into `src/components/widgets/AddNewWidgetBtn/AddNewWidgetBtn.tsx` to get idea to implement

2024-01-29 14:04 UTC, yashchaudhari008 commented on src/components/Footer/GithubIcon.tsx
THIS FILE SHOULD BE DELETED as we are using **Font-Awesome** for icons

2024-01-29 14:06 UTC, yashchaudhari008 commented on src/components/Footer/footer.module.scss
Also try to use `px` instead of `rem`. As we are using px as standard for this project

2024-01-29 14:10 UTC, yashchaudhari008 requested changes
Also current alignment looks little off:

| Current | Expected |
| --- | --- |
| <img width="230" alt="image" src="https://github.com/yashchaudhari008/minime/assets/29065088/a967c94f-a899-4b1c-bf2f-05798185c9da"> | <img width="589" alt="image" src="https://github.com/yashchaudhari008/minime/assets/29065088/21c51a76-9b3c-442b-bf5e-c32edc4689eb"> |

2024-01-29 14:13 UTC, yashchaudhari008 commented
Also please mention yourself on the issue, so that I can assign it to you

2024-01-29 16:45 UTC, linyers commented
While making the changes, I encountered a bug with the font-weight of the Inter font. I was able to resolve it, but I'm unsure whether to include it in this pull request or create a new one.

2024-01-30 02:56 UTC, yashchaudhari008 commented
@linyers What's the exact issue?

2024-01-30 14:23 UTC, linyers commented
The issue was with the Inter font. When attempting to increase the weight of the Inter font, it remained at the default (400). I also noticed that certain components were using a different weight than the default, and the weight stayed at 400 even when set to 800. So, I imported various weights for the Inter font, and the issue was resolved. 

in `src/index.scss`
`@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900...");`

2024-01-30 17:51 UTC, yashchaudhari008 commented
Can you check whether this happens only when Chrome is opened in incognito mode? Because this is happening in my case!

2024-01-30 18:01 UTC, yashchaudhari008 commented
Also, can you push your recent changes and request re-review?

2024-01-31 01:19 UTC, linyers commented
> Can you check whether this happens only when Chrome is opened in incognito mode? Because this is happening in my case!

I have been noticing that this seems to be some issue with browsers. I tested it on Chrome, Brave, and Firefox. I'm sharing some links that discuss this:

https://stackoverflow.com/questions/22001035/font-weight-ignored-in-chrome
https://github.com/tailwindlabs/tailwindcss/issues/1402

I have tried different solutions, and the one that worked for me was importing the weights I am going to use: 

```
@import url("http://fonts.googleapis.com/css?family=Open+Sans:400,300,500,800");
```

2024-01-31 08:19 UTC, yashchaudhari008 approved these changes
Looks Good! Thanks for contributing

2024-01-31 08:21 UTC, merged